### ISSUE TITLE
关于train_cnn

### ISSUE THREAD

**Issue by Csh1752** [munhouiani/Deep-Packet#12]
win10系统，python3.9，使用下载的train_test_data中的数据运行train_cnn，出现如下报错：
Traceback (most recent call last):
  File "E:\Deep-Packet-master\train_cnn.py", line 28, in <module>
    main()
  File "D:\py\python3.9\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "D:\py\python3.9\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "D:\py\python3.9\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\py\python3.9\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "E:\Deep-Packet-master\train_cnn.py", line 20, in main
    train_application_classification_cnn_model(data_path, model_path, gpu)
  File "E:\Deep-Packet-master\ml\utils.py", line 42, in train_application_classification_cnn_model
    train_cnn(c1_kernel_size=4, c1_output_dim=200, c1_stride=3, c2_kernel_size=5, c2_output_dim=200, c2_stride=1,
  File "E:\Deep-Packet-master\ml\utils.py", line 32, in train_cnn
    model = CNN(hparams).float()
  File "E:\Deep-Packet-master\ml\model.py", line 15, in __init__
    self.hparams = hparams
  File "D:\py\python3.9\lib\site-packages\torch\nn\modules\module.py", line 1178, in __setattr__
    object.__setattr__(self, name, value)
AttributeError: can't set attribute

**Comment by munhouiani** [comment]
Code 已更新
