### ISSUE TITLE
运行train_cnn.py出现错误

### ISSUE THREAD

**Issue by QzP-QD** [munhouiani/Deep-Packet#15]
Traceback (most recent call last):
  File "train_cnn.py", line 27, in <module>
    main()
  File "/home/ubuntu/lxd-storage/qizhipeng/anaconda3/envs/torchEnv/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/lxd-storage/qizhipeng/anaconda3/envs/torchEnv/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/lxd-storage/qizhipeng/anaconda3/envs/torchEnv/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/lxd-storage/qizhipeng/anaconda3/envs/torchEnv/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "train_cnn.py", line 21, in main
    train_traffic_classification_cnn_model(data_path, model_path, gpu)
  File "/home/ubuntu/lxd-storage/qizhipeng/Deep-Packet/ml/utils.py", line 54, in train_traffic_classification_cnn_model
    logger=logger)
  File "/home/ubuntu/lxd-storage/qizhipeng/Deep-Packet/ml/utils.py", line 35, in train_cnn
    model = CNN(hparams).float()
  File "/home/ubuntu/lxd-storage/qizhipeng/Deep-Packet/ml/model.py", line 15, in __init__
    self.hparams = hparams
  File "/home/ubuntu/lxd-storage/qizhipeng/anaconda3/envs/torchEnv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 826, in __setattr__
    object.__setattr__(self, name, value)
AttributeError: can't set attribute
找了好久没找到问题出在哪，流程是正确的，请问知道原因嘛？

**Comment by munhouiani** [comment]
Code 已更新
