### ISSUE TITLE
KetError:length when run train_cnn.py

### ISSUE THREAD

**Issue by HebeLyu** [munhouiani/Deep-Packet#35]
Traceback (most recent call last):
  File "/home/inspur/lvzhuo/metrics learning/MultiModel_Plus/compare/deep_pac/train_cnn.py", line 35, in <module>
    main(data_dir + 'etc/train_test_data/train.parquet','model/etc.cnn.model',task="app",cls_num=8)
  File "/home/inspur/lvzhuo/metrics learning/MultiModel_Plus/compare/deep_pac/train_cnn.py", line 23, in main
    train_application_classification_cnn_model(data_path, model_path,cls_num)
  File "/home/inspur/lvzhuo/metrics learning/MultiModel_Plus/compare/deep_pac/ml/utils.py", line 290, in train_application_classification_cnn_model
    train_cnn(
  File "/home/inspur/lvzhuo/metrics learning/MultiModel_Plus/compare/deep_pac/ml/utils.py", line 231, in train_cnn
    trainer.fit(model)
  File "/home/inspur/anaconda3/envs/deep_packet/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 696, in fit
    self._call_and_handle_interrupt(
  File "/home/inspur/anaconda3/envs/deep_packet/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/inspur/anaconda3/envs/deep_packet/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 735, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/inspur/anaconda3/envs/deep_packet/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1166, in _run
    results = self._run_stage()
  File "/home/inspur/anaconda3/envs/deep_packet/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1252, in _run_stage
    return self._run_train()
  File "/home/inspur/anaconda3/envs/deep_packet/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1283, in _run_train
    self.fit_loop.run()
  File "/home/inspur/anaconda3/envs/deep_packet/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 195, in run
    self.on_run_start(*args, **kwargs)
  File "/home/inspur/anaconda3/envs/deep_packet/lib/python3.10/site-packages/pytorch_lightning/loops/fit_loop.py", line 211, in on_run_start
    self.trainer.reset_train_dataloader(self.trainer.lightning_module)
  File "/home/inspur/anaconda3/envs/deep_packet/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1812, in reset_train_dataloader
    self.train_dataloader = self._data_connector._request_dataloader(RunningStage.TRAINING)
  File "/home/inspur/anaconda3/envs/deep_packet/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 453, in _request_dataloader
    dataloader = source.dataloader()
  File "/home/inspur/anaconda3/envs/deep_packet/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 526, in dataloader
    return self.instance.trainer._call_lightning_module_hook(self.name, pl_module=self.instance)
  File "/home/inspur/anaconda3/envs/deep_packet/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1550, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/home/inspur/lvzhuo/metrics learning/MultiModel_Plus/compare/deep_pac/ml/utils.py", line 112, in train_dataloader
    dataset_dict = datasets.load_dataset(self.hparams.data_path)
  File "/home/inspur/anaconda3/envs/deep_packet/lib/python3.10/site-packages/datasets/load.py", line 1675, in load_dataset
    builder_instance = load_dataset_builder(
  File "/home/inspur/anaconda3/envs/deep_packet/lib/python3.10/site-packages/datasets/load.py", line 1478, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
  File "/home/inspur/anaconda3/envs/deep_packet/lib/python3.10/site-packages/datasets/builder.py", line 347, in __init__
    self.info = DatasetInfo.from_directory(self._cache_dir)
  File "/home/inspur/anaconda3/envs/deep_packet/lib/python3.10/site-packages/datasets/info.py", line 284, in from_directory
    return cls.from_dict(dataset_info_dict)
  File "/home/inspur/anaconda3/envs/deep_packet/lib/python3.10/site-packages/datasets/info.py", line 289, in from_dict
    return cls(**{k: v for k, v in dataset_info_dict.items() if k in field_names})
  File "<string>", line 20, in __init__
  File "/home/inspur/anaconda3/envs/deep_packet/lib/python3.10/site-packages/datasets/info.py", line 145, in __post_init__
    self.features = Features.from_dict(self.features)
  File "/home/inspur/anaconda3/envs/deep_packet/lib/python3.10/site-packages/datasets/features/features.py", line 1597, in from_dict
    obj = generate_from_dict(dic)
  File "/home/inspur/anaconda3/envs/deep_packet/lib/python3.10/site-packages/datasets/features/features.py", line 1280, in generate_from_dict
    return {key: generate_from_dict(value) for key, value in obj.items()}
  File "/home/inspur/anaconda3/envs/deep_packet/lib/python3.10/site-packages/datasets/features/features.py", line 1280, in <dictcomp>
    return {key: generate_from_dict(value) for key, value in obj.items()}
  File "/home/inspur/anaconda3/envs/deep_packet/lib/python3.10/site-packages/datasets/features/features.py", line 1284, in generate_from_dict
    return Sequence(feature=generate_from_dict(obj["feature"]), length=obj["length"])
KeyError: 'length'

**Comment by munhouiani** [comment]
Which version of `datasets` are you using?
