### ISSUE TITLE
docker运行时，调用spark时出错.

### ISSUE THREAD

**Issue by chunxiao369** [munhouiani/Deep-Packet#7]
您好。在生成测试集和训练集时出错。
docker中未看到安装jdk，jdk安装步骤或者新的docker能提供不？
python create_train_test_set.py -s processed_data -t train_test_data
JAVA_HOME is not set
Traceback (most recent call last):
  File "create_train_test_set.py", line 185, in <module>
    main()
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "create_train_test_set.py", line 153, in main
    .config('spark.driver.host', '127.0.0.1')
  File "/opt/conda/lib/python3.7/site-packages/pyspark/sql/session.py", line 173, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
  File "/opt/conda/lib/python3.7/site-packages/pyspark/context.py", line 367, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/opt/conda/lib/python3.7/site-packages/pyspark/context.py", line 133, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/opt/conda/lib/python3.7/site-packages/pyspark/context.py", line 316, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
  File "/opt/conda/lib/python3.7/site-packages/pyspark/java_gateway.py", line 46, in launch_gateway
    return _launch_gateway(conf)
  File "/opt/conda/lib/python3.7/site-packages/pyspark/java_gateway.py", line 108, in _launch_gateway
    raise Exception("Java gateway process exited before sending its port number")
Exception: Java gateway process exited before sending its port number

**Comment by imarom** [comment]
Any update on that ?

**Comment by zbdxkzk** [comment]
请问 您的pre-trained模型可以使用吗？
运行有个错误
TypeError: __init__() missing 1 required positional argument: 'hparams'

**Comment by munhouiani** [comment]
Code updated.
